In [1]:
# Importing libraries
import numpy as np

### Numpy arrays

The simplest ways to create an array is to pass a list of numbers to `np.array()` creating an one axis array better known as a vector

A numpy array provides the following attributes:
1) .ndim shows the number of axes in an array

2) .shape a tuple of integers indicating the size of the array in each dimension 

3) .size shows how many elements are in the array

In [2]:
# Multiplication of two arrays
a = np.array([1, 2, 4])
b = np.array([5, 6, 7])
print("Multiplication of both arrays: ", a * b)

Multiplication of both arrays:  [ 5 12 28]


In [4]:
# Inspecting each atributes of the numpy array
v = np.array([1, 2, 3, 4, 6])

print("Ndim: ", v.ndim)
print("Shape: ", v.shape)
print("Size: ", v.size)

Ndim:  1
Shape:  (5,)
Size:  5


### Matrices

It is possible to create an array by passing a sequence of lists to a numpy array. This produces an array of two axes, which is referred to a matrix

In [7]:
# Declaring our lists
l = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]

# Adding sequence of list to a numpy array
matrix = np.array(l)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
# Exploring their attributes
print("Ndim: ", matrix.ndim)
print("Shape: ", matrix.shape) # Matrix represented by N rows and M columns
print("Size: ", matrix.size)

Ndim:  2
Shape:  (3, 3)
Size:  9
