In [1]:
# Importing libraries
import numpy as np

### Numpy arrays

The simplest ways to create an array is to pass a list of numbers to `np.array()` creating an one axis array better known as a vector

A numpy array provides the following attributes:
1) .ndim shows the number of axes in an array

2) .shape a tuple of integers indicating the size of the array in each dimension 

3) .size shows how many elements are in the array

In [2]:
# Multiplication of two arrays
a = np.array([1, 2, 4])
b = np.array([5, 6, 7])
print("Multiplication of both arrays: ", a * b)

Multiplication of both arrays:  [ 5 12 28]


In [3]:
# Inspecting each atributes of the numpy array
v = np.array([1, 2, 3, 4, 6])

print("Ndim: ", v.ndim)
print("Shape: ", v.shape)
print("Size: ", v.size)

Ndim:  1
Shape:  (5,)
Size:  5


### Matrices

It is possible to create an array by passing a sequence of lists to a numpy array. This produces an array of two axes, which is referred to a matrix

In [4]:
# Declaring our lists
l = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]

# Adding sequence of list to a numpy array
matrix = np.array(l)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
# Exploring their attributes
print("Ndim: ", matrix.ndim)
print("Shape: ", matrix.shape) # Matrix represented by N rows and M columns
print("Size: ", matrix.size)

Ndim:  2
Shape:  (3, 3)
Size:  9


In [6]:
# To avoid syntax errors, understand the differences between vectors, arrays and columns
vec = np.array([2, 5, 9])
row = np.array([[2, 5, 9]])
col = np.array([[2], [5], [9]])

# Remark that matrix have double pairs of brackets, while vectors only have one pair
print("-------Vector-------")
print(vec, "shape -> ", vec.shape)
print("-------Matrix one row-------")
print(row, "shape -> ", row.shape)
print("-------Matrix one column-------")
print(col, "shape -> ", col.shape)

-------Vector-------
[2 5 9] shape ->  (3,)
-------Matrix one row-------
[[2 5 9]] shape ->  (1, 3)
-------Matrix one column-------
[[2]
 [5]
 [9]] shape ->  (3, 1)


### Non-dimensional arrays

We have no limit with respect to the nestling level of lists added to a numpy array. Here we create an array with three axes better known as volume

In [7]:
lists = [[[0, 1, 2], [3, 4, 5], [6, 7, 8]], [[8, 7, 6], [5, 4, 3], [2, 1, 0]]]
volume = np.array(lists)
print(volume)

[[[0 1 2]
  [3 4 5]
  [6 7 8]]

 [[8 7 6]
  [5 4 3]
  [2 1 0]]]


In [8]:
# Inspecting their attributes
print("Ndim: ", volume.ndim)
print("Shape: ", volume.shape) # Two matrices represented by N rows and M columns
print("Size: ", volume.size)

Ndim:  3
Shape:  (2, 3, 3)
Size:  18


### Reshaping

We can change the shape of an array with different commands:
1) **.reshape** reconfigures the array to a new shape
2) **.ravel** stretches the array into a vector

**Note:** we create an array of random integers, in the `randint()` function the first parameter states the range of the numbers (0 to 9) and size declares the dimensions of the matrix (3 rows and 4 columns)

In [9]:
# Creating a numpy array of random integers
x = np.random.randint(10, size=(3,4))
y = x.reshape(6, 2)
z = x.ravel()

# Printing information of their shape
print("-------X-------")
print(x, "shape -> ", x.shape)
print("-------Y-------")
print(y, "shape -> ", y.shape)
print("-------Z-------")
print(z, "shape -> ", z.shape)

-------X-------
[[7 0 6 9]
 [1 2 4 8]
 [7 5 6 6]] shape ->  (3, 4)
-------Y-------
[[7 0]
 [6 9]
 [1 2]
 [4 8]
 [7 5]
 [6 6]] shape ->  (6, 2)
-------Z-------
[7 0 6 9 1 2 4 8 7 5 6 6] shape ->  (12,)


Reshape doesn't make a copy of the data, it produces a new view of the original array. A view behaves as a regular array, except that its elements are **shared**  with the array from which was created

In [10]:
a = np.array([4, 8, 7, 2, 5, 1])

# Here we are sharing data from a to create a new view of the array stored in b
b = a.reshape(2, 3)

print("Array a ->", a)
print("Reshaped array")
print(b)

Array a -> [4 8 7 2 5 1]
Reshaped array
[[4 8 7]
 [2 5 1]]


### Important Point
The reshaped arrays share the same elements of the original array, without making an actual copy of the data. So, any modification on the reshaped array is performed in the original array

In [11]:
b[1,0] = -8 # This modification will occur also in the original array

print("------a------")
print(a)
print("------b------")
print(b)

------a------
[ 4  8  7 -8  5  1]
------b------
[[ 4  8  7]
 [-8  5  1]]


### Array indexing

When indexing a vector of one dimension consider the next advices:
- A single element is extracted by giving it positions
- The index must be between 0 and n - 1
- Negative integers can be used for integer like -1 or -size

In [12]:
# Declaring our vector
vec = np.array([2.1, 3.4, 1, 5.5, 3, 8,7])

print(vec)
print("Vector index 2: ", vec[2])
print("Vector index -1: ", vec[-1])

[2.1 3.4 1.  5.5 3.  8.  7. ]
Vector index 2:  1.0
Vector index -1:  7.0


We can also do this for multidimensional arrays, consider the next advices:
- A single element is extracted by giving a tuple of integers, one for each axis
- The integers must be between 0 and shape[n] - 1

In [15]:
m = np.array([[1, 3, 4], [2, 5, 8], [3, 1, 4], [7, 1, 9]])

# Printing the value in index [1, 2]
print(m)
print("Index value: ", m[1,2])

[[1 3 4]
 [2 5 8]
 [3 1 4]
 [7 1 9]]
Index value:  8


In [19]:
v = np.array([[[1, 3, 1], [2, 5, 1]], [[5, 9, 0], [5, 7, 3]]])

# Printing the value at index [1,0,-2]
print(v)
print("Index value: ", v[1,0,-2])

[[[1 3 1]
  [2 5 1]]

 [[5 9 0]
  [5 7 3]]]
Index value:  9


### Slicing

You can extract a contiguous subarray using the slice notation

In [22]:
print("Original vector: ", vec)

# vector[start:stop] it stops at i - 1
print("Vector [1:3] ", vec[1:3])

# vector[start:] until the end
print("Vector index to so on ", vec[2:])

# Note when [:] prints all items

Original vector:  [2.1 3.4 1.  5.5 3.  8.  7. ]
Vector [1:3]  [3.4 1. ]
Vector index to so on  [1.  5.5 3.  8.  7. ]


In [29]:
# Applying it to matrix, do it for any axis of a multidimensional array
print(m)
print("Matrix [2:] ", m[1, :])
print("Matrix [1:3, :2] ", m[1:3, :3])

[[1 3 4]
 [2 5 8]
 [3 1 4]
 [7 1 9]]
Matrix [2:]  [2 5 8]
Matrix [1:3, :2]  [[2 5 8]
 [3 1 4]]
