In [1]:
# Importing standard libraries
import math as mt
import numpy as np
import time
import os

# Import pytorch
import torch

### Setting the seed

In a machine learning framework, Pytorch provides some functions that are stochastic as generating random numbers. However, a good practice is to setup your code to use the same exact random numbers

In [2]:
torch.manual_seed(42)

### Tensors

Tensors are equivalent to numpy arrays with the addition of support for GPU acceleration. For instance:
- A vector is a 1-D tensor
- A matrix is a 2-D tensor

Most common functions of numpy can be also used on tensors. With this in mind, we're able to convert most tensors to numpy arrays

`Note: Working with networks will involve the use of tensors of various shapes and dimensions` 

### Initialize a tensor

There are different ways to initialize a tensor, the simplest way is to call `torch.Tensor` with the next arguments:
1) Represents the length of dimension 0 of the tensor
2) Represents the length of dimension 1 of the tensor
3) Represents the length of dimension 2 of the tensor

In [3]:
x = torch.Tensor(2, 3, 4)
print(x)

tensor([[[1.5766e-19, 1.0256e-08, 1.0313e-08, 3.1300e+12],
         [1.7343e-07, 6.4475e-10, 4.2186e-08, 1.3034e+16],
         [2.1707e-18, 7.0952e+22, 1.7748e+28, 1.8176e+31]],

        [[7.2708e+31, 5.0778e+31, 3.2608e-12, 1.7728e+28],
         [7.0367e+22, 2.1715e-18, 2.0546e+20, 1.3149e+22],
         [2.1589e-04, 6.5548e-10, 1.6517e-04, 1.0538e-11]]])


Also, you can assign direct values to the tensor during initialization

In [4]:
# Create a tensor from a nested list
x = torch.Tensor([[1, 2], [3, 4]])
print(x)

tensor([[1., 2.],
        [3., 4.]])


In [5]:
# Use of the rand function to create random values between 0 and 1
x = torch.rand(2, 3, 4)
print(x)

tensor([[[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]],

        [[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]])


You can obtain the shape of a tensor in the same way as numpy, or use the `size` method

In [6]:
shape = x.shape
print("Shape: ", shape)

size = x.size()
print("Size: ", size)

# Print the dimension of the tensor
dim1, dim2, dim3 = x.size()
print("Size: ", dim1, dim2, dim3)

Shape:  torch.Size([2, 3, 4])
Size:  torch.Size([2, 3, 4])
Size:  2 3 4
