In [1]:
# Importing standard libraries
import math as mt
import numpy as np
import time
import os

# Import pytorch
import torch

### Setting the seed

In a machine learning framework, Pytorch provides some functions that are stochastic as generating random numbers. However, a good practice is to setup your code to use the same exact random numbers

In [2]:
torch.manual_seed(42)

### Tensors

Tensors are equivalent to numpy arrays with the addition of support for GPU acceleration. For instance:
- A vector is a 1-D tensor
- A matrix is a 2-D tensor

Most common functions of numpy can be also used on tensors. With this in mind, we're able to convert most tensors to numpy arrays

`Note: Working with networks will involve the use of tensors of various shapes and dimensions` 

### Initialize a tensor

There are different ways to initialize a tensor, the simplest way is to call `torch.Tensor` with the next arguments:
1) Represents the length of dimension 0 of the tensor
2) Represents the length of dimension 1 of the tensor
3) Represents the length of dimension 2 of the tensor

In [3]:
x = torch.Tensor(2, 3, 4)
print(x)

tensor([[[0.0000e+00, 0.0000e+00, 7.7052e+31, 7.2148e+22],
         [1.5766e-19, 1.0256e-08, 1.0313e-08, 3.1472e+12],
         [6.9362e-07, 4.1031e-08, 6.5645e-07, 1.2469e+16]],

        [[2.1707e-18, 7.0952e+22, 1.7748e+28, 1.8176e+31],
         [7.2708e+31, 5.0778e+31, 3.2608e-12, 1.7728e+28],
         [7.0367e+22, 2.1715e-18, 3.3828e+21, 3.3559e-06]]])


Also, you can assign direct values to the tensor during initialization

In [4]:
# Create a tensor from a nested list
x = torch.Tensor([[1, 2], [3, 4]])
print(x)

tensor([[1., 2.],
        [3., 4.]])


In [5]:
# Use of the rand function to create random values between 0 and 1
x = torch.rand(2, 3, 4)
print(x)

tensor([[[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]],

        [[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]])


You can obtain the shape of a tensor in the same way as numpy, or use the `size` method

In [7]:
shape = x.shape
print("Shape: ", shape)

size = x.size()
print("Size: ", size)

# Print the dimension of the tensor
dim1, dim2, dim3 = x.size()
print("Size: ", dim1, dim2, dim3)

Shape:  torch.Size([2, 3, 4])
Size:  torch.Size([2, 3, 4])
Size:  2 3 4


### Tensor to numpy

Tensores can be turned to numpy arrays, and viceversa. To transform a numpy array into a tensor, we can use the function `torch.from_numpy`

In [10]:
np_array = np.array(([1, 2], [3, 4]))

# Turning a numpy array to tensor
tensor = torch.from_numpy(np_array)

print("Numpy array: ", np_array)
print("Pytorch tensor: ", tensor)

Numpy array:  [[1 2]
 [3 4]]
Pytorch tensor:  tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [11]:
# Turning back a tensor to a numpy array
tensor = torch.arange(4)
np_array = tensor.numpy()

print("Pytorch tensor: ", tensor)
print("Numpy array: ", np_array)

Pytorch tensor:  tensor([0, 1, 2, 3])
Numpy array:  [0 1 2 3]


`Note: To do the conversion the tensor must be on the CPU, and not on the GPU`

### Operations with tensors

Most of the numpy operations can also be done in tensors. Some of the simpliest operations are the next ones:

In [12]:
# Adding two tensors
x1 = torch.rand(2, 3)
x2 = torch.rand(2, 3)
y = x1 + x2

print("Total sum: ", y)

Total sum:  tensor([[1.0569, 0.3448, 1.2448],
        [0.7826, 0.8848, 0.8151]])


The code above creates a new tensor with the sum of two inputs. However, we can you in place operations that are applied directly on the memory of a tensor.

With this in mind, we can change the values of x1 without re-accesing the values of x2 before the operation

In [14]:
# Initializing tensors
x1 = torch.rand(2, 3)
x2 = torch.rand(2, 3)
print("Original x2: ", x2)

x2.add_(x1) # In place operations are marked with a underscore postfix
print("X2 add: ", x2)

Original x2:  tensor([[0.6440, 0.7071, 0.6581],
        [0.4913, 0.8913, 0.1447]])
X2 add:  tensor([[1.3979, 0.9024, 0.6632],
        [0.7981, 1.0078, 1.0550]])


In [18]:
# Changing the shape of a tensor
x = torch.arange(6)
print("Original: ", x)

# Re-organized shape with the same order of elements
x = x.view(2,3)
print("Re-organized: ", x)

# Swapping dimensions 0 and 1
x = x.permute(1, 0)
print("Swapping: ", x)

Original:  tensor([0, 1, 2, 3, 4, 5])
Re-organized:  tensor([[0, 1, 2],
        [3, 4, 5]])
Swapping:  tensor([[0, 3],
        [1, 4],
        [2, 5]])
