### Exercises of numpy

In [2]:
# Importing the libraries
import numpy as np

In [3]:
# Creating a vector of length 5 with zeros
z = np.zeros(5)
print("Array: ", z)

Array:  [0. 0. 0. 0. 0.]


In [4]:
# Creating a matrix with 8 rows and 4 columns filled with ones
m = np.ones(shape=(8,4))
print(m)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
# Getting the number of rows and columns in a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

print("Number of rows: ", matrix.shape[0])
print("Number of columns: ", matrix.shape[1])

Number of rows:  4
Number of columns:  3


In [6]:
# Different ways to reshape an array into a vector
v = np.array([[[5, 3, 2],
               [3, 2, 7],
               [8, 3, 7]],

               [[5, 6, 3],
                [9, 1, 3],
                [5, 1, 9]]])

# Using the reshape function
v_new = v.reshape(3, 6)
v_ravel = v.ravel()

print("------Reshape function------")
print(v_new)
print("------Ravel function--------")
print(v_ravel)

------Reshape function------
[[5 3 2 3 2 7]
 [8 3 7 5 6 3]
 [9 1 3 5 1 9]]
------Ravel function--------
[5 3 2 3 2 7 8 3 7 5 6 3 9 1 3 5 1 9]


### Index and slicing exercises

In [11]:
# Create a vector of size 10 filled with zero, and set the first and last element to 1
vec = np.zeros(10)
vec[0] = 1
vec[-1] = 1
print(vec)

[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


In [13]:
# Making a swap of the 2nd and 4th index
s = np.array([5, 1, 13, 2, 12, 0])

# Before making the swap
print(s)

temp = s[2]
s[2] = s[4]
s[4] = temp

# After making the swap
print(s)

[ 5  1 13  2 12  0]
[ 5  1 12  2 13  0]
